### ISSUE TITLE
Failed install bugged my yunohost server

### ISSUE THREAD

**Issue by WilyWildWilly** [YunoHost-Apps/minidlna_ynh#15]
Hello,

tryingto install this on yunohost on debian 9.7 gave this: 
```
Action

GET /apps
{"locale":"en","installed":""}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 252, in app_list
    with open(json_path) as json_list:
IOError: [Errno 2] No such file or directory: u'/var/cache/yunohost/repo/minidlna.json'
```
I get this error everytime I try to access my apps as admin or other sections of the admin menu.

**Comment by WilyWildWilly** [comment]
```
XXXX@XXXX:/blahblah/cache/yunohost# yunohost app fetchlist --debug
207  DEBUG loading actions map namespace 'yunohost'
234  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
235  DEBUG initializing base actions map parser for cli
237  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
352  DEBUG lock has been acquired
391  DEBUG loading python module yunohost.app took 0.039s
391  INFO processing action [22721.1]: yunohost.app.fetchlist with args={'url': None, 'name': None}
1064 DEBUG Attempting to fetch list yunohost at https://app.yunohost.org/official.json
1073 DEBUG Starting new HTTPS connection (1): app.yunohost.org
1481 DEBUG https://app.yunohost.org:443 "GET /official.json HTTP/1.1" 200 42893
1574 SUCCESS The application list yunohost has been fetched
1574 DEBUG Attempting to fetch list minidlna at https://github.com/YunoHost-Apps/minidlna_ynh
1576 DEBUG Starting new HTTPS connection (1): github.com
2712 DEBUG https://github.com:443 "GET /YunoHost-Apps/minidlna_ynh HTTP/1.1" 200 None
2860 ERROR Retrieved file for application list minidlna is not valid
2861 DEBUG action [22721.1] executed in 2.470s
2862 DEBUG lock has been released
```

**Comment by maniackcrudelis** [comment]
Hello WilyWildWilly

How did you install the app ?
There's no reason to have a list named `/var/cache/yunohost/repo/minidlna.json`

**Comment by WilyWildWilly** [comment]
I installedthe app through the yunohost app install menu.

**Comment by maniackcrudelis** [comment]
Sure, you didn't mixed up with the menu used to install a new app list ?
If you have the community list loaded in your YunoHost, minidlna is already available into it.
